### PR TITLE
add 6to5-runtime as dep for selfCantained transform

### PR DESCRIPTION
**Pull request by kolodny**

### CODE REVIEW

**Comment by kolodny** [comment]
It would be nice if something like this just worked:

```bash
echo 'async function odd(n) { return n === 1 ? true : await odd(n-1) }' | 6to5 --experimental --optional selfContained | node
```

**Comment by sebmck** [comment]
This wont do anything unless you're inside `node_modules/6to5` so it has no benefit to users.

**Comment by kolodny** [comment]
Good point. Since a lot of projects are already using 6to5 and/or 6to5 being installed globally, would you be open to a PR for another transform that just does `require('6to5/polyfil')` ?

**Comment by sebmck** [comment]
I don't particularly like to encourage the use of the polyfill because it's globally polluting, I'm also not sure what the benefit would be?

**Pull request closed without merging**
