### PR TITLE
Regexify array.

### PR DESCRIPTION
**Pull request by hemanth**
Recursive strategy.

//cc @sebmck

### CODE REVIEW

**Comment by sebmck** [comment]
What's the point?

**Comment by hemanth** [comment]
Without the `return` for an array we would get `TypeError: illegal type: foo|bar for regexify` 

(yet to test :/)

**Comment by sebmck** [comment]
Nope, it'd hit `if (isString(val)) return new RegExp(val);`.

**Comment by hemanth** [comment]
Duh! Yeah, sorry my bad, I'm doing a module for the same and in my code I had `string` above `array` :/

```js
if (isString(val)) {
    return new RegExp(val);
  }
  if (Array.isArray(val)) {
    return regexify(val.join('|'));
  }
```

**Comment by hemanth** [comment]
@sebmck If you want it to be more modular, I can do a PR for [regexify](https://www.npmjs.com/package/regexify)

**Comment by sebmck** [comment]
@hemanth I'm fine with having it inline. Thanks though!

**Comment by hemanth** [comment]
:+1:

**Pull request closed without merging**
