### PR TITLE
Handle esprima-like AST catch clause in a TryStatement. Fixes #473

### LINKED ISSUE #473: Regenerator esprima generated ast discrepancy
Esprima has an old bug that makes it put the `CatchClause` node in a `handlers` field on the TryStatement node, whereas the official Mozilla Parser API defines it as a `handler` property -- which acorn does just fine.

This makes 6to5 unable to print try/catch statements generated by regenerator. To reproduce:
```
$ 6to5 --include-regenerator
function *x() {}
```
Observe the regenerator runtime stripped out from all it's catch clauses.

cc @benjamn maybe this can be fixed in ast-types

### PR DESCRIPTION
**Pull request by amasad**

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Would be nice to have a test that fails without this.

**Comment by amasad** [comment]
I usually add failing tests, but this one it proved a bit harder, because the tests are structured in a way text in and text out. I didn't see how I can have ast-to-ast tests. Or ast-to-text tests. Let me know what's the best way to add it and I'll do it

**Comment by amasad** [comment]
Do you think I should add it as a transformation test?

**Comment by eventualbuddha** [comment]
@amasad Apologies if this is explained elsewhere, but how did you run into this bug? Presumably you have JS input from somewhere and are getting JS out. Is there more than just 6to5 in the pipeline? Are you giving 6to5 an AST?

**Comment by amasad** [comment]
6to5 calls into regenerator and passes it the AST which regenerator manipulates. When regenerator generates a try/catch statement the AST is based on esprima which differs from Acorn and Mozilla Parser API. So when time comes for 6to5 to print the AST it can't print try/catch properly because it doesn't recognize the AST structure. #473

**Comment by amasad** [comment]
I added tests

**Comment by sebmck** [comment]
Great, thanks! The test isn't very future-proof but it'll have to do for now.

**Comment by amasad** [comment]
It'd be great to start doing more "functional" tests. i.e. eval the code and make sure it runs. It's less fragile than ast or text comparison.

I thought the test passed locally but looking at the CI, did it pass?

**Comment by sebmck** [comment]
@amasad There's `exec` tests. So instead of having an `actual.js` and an `expected.js` you can have an `exec.js` that has access to the `assert`. See [playground/memoization-assignment-operator/exec.js](https://github.com/6to5/6to5/blob/master/test/fixtures/transformation/playground/memoization-assignment-operator/exec.js) for example.

**Comment by amasad** [comment]
oh cool! that's much better suited for this

**Comment by sebmck** [comment]
Released as of 2.11.2

**Pull request merged**
