### PR TITLE
Added complete TCO (tail call optimization).

### LINKED ISSUE #256: Support for tail call optimization
http://www.2ality.com/2014/04/call-stack-size.html
*ECMAScript 6 will have tail call optimization: If a function call is the last action in a function, it is handled via a “jump”, not via a “subroutine call”. That means that, if you slightly rewrote computeMaxCallStackSize(), it would run forever under ECMAScript 6 (in strict mode)*

**Tail call recursion**
```js
function fac_times(n, acc) {
	return (n == 0) ? acc : fac_times(n - 1, acc * n);
}

function factorial(n) {
	return fac_times(n, 1);
}
```

**After optimization**
```js
function fac_times(n, acc) {
	while (true) {
		if (n == 0) {
			return acc;
		}
	
		var old_n = n,
			old_acc = acc;
	
		n = old_n - 1;
		acc = old_acc * old_n;
	}
}

function factorial(n) {
	return fac_times(n, 1);
}
```

### PR DESCRIPTION
**Pull request by RReverser**
Works across functions and generates simpler and faster code than #701.
Works even across files when used in conjunction with `runtime` option.

Closes #256.

### CODE REVIEW

**Comment by phpnode** [comment]
whoa, this is awesome!

**Comment by sebmck** [comment]
🎈🎊🎉 This is amazing! 🎉🎊🎈

**Comment by zloirock** [comment]
:thumbsup:

**Comment by kevinb7** [comment]
:+1:

**Comment by RReverser** [comment]
Actually this can be cleaned up a bit more, but going to sleep, will do that tomorrow. Thanks everyone!

**Comment by elierotenberg** [comment]
:+1:

**Comment by benchekroundev** [comment]
(y)

**Comment by raganwald** [comment]
Is this in the REPL yet? I tried compiling this:

    const mapWith = (fn, [first, ...rest], prepend = []) =>
      first === undefined
        ? prepend
        : mapWith(fn, rest, [...prepend, fn(first)]);

And I got this, a “Plain Old Recursive Function:”

    "use strict";

    var _toArray = function (arr) { return Array.isArray(arr) ? arr : Array.from(arr); };

    var mapWith = function (fn, _ref) {
      var _ref2 = _toArray(_ref);

      var first = _ref2[0];
      var rest = _toArray(_ref2).slice(1);

      var prepend = arguments[2] === undefined ? [] : arguments[2];
      return first === undefined ? prepend : mapWith(fn, rest, [].concat(_toArray(prepend), [fn(first)]));
    };

I would expect this to compile the tail call into a trampoline invocation. Am I misunderstanding how to write a function that triggers the optimization?

**Comment by sebmck** [comment]
I haven't pushed out a new release yet, no.

On Sunday, 8 February 2015, Reg Braithwaite <notifications@github.com>
wrote:

> Is this in the REPL yet? I tried compiling this:
>
> const mapWith = (fn, [first, ...rest], prepend = []) =>
>   first === undefined
>     ? prepend
>     : mapWith(fn, rest, [...prepend, fn(first)]);
>
> And I got this, a "Plain Old Recursive Function:"
>
> "use strict";
>
> var _toArray = function (arr) { return Array.isArray(arr) ? arr : Array.from(arr); };
>
> var mapWith = function (fn, _ref) {
>   var _ref2 = _toArray(_ref);
>
>   var first = _ref2[0];
>   var rest = _toArray(_ref2).slice(1);
>
>   var prepend = arguments[2] === undefined ? [] : arguments[2];
>   return first === undefined ? prepend : mapWith(fn, rest, [].concat(_toArray(prepend), [fn(first)]));
> };
>
> I would expect this to compile the tail call into a trampoline invocation.
> Am I misunderstanding how to write a function that triggers the
> optimization?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/6to5/6to5/pull/714#issuecomment-73391728>.
>


-- 
Sebastian McKenzie

**Comment by raganwald** [comment]
> I haven't pushed out a new release yet, no.

Thanks for the :rocket: :email: :exclamation:

**Comment by cesarandreu** [comment]
:+1:

**Comment by RnbWd** [comment]
:raised_hands:

**Comment by kolodny** [comment]
:trophy:

**Comment by jabbrass** [comment]
Nice, looking forward to using recursion full-time over loops! Thanks for the hard work.

**Comment by sebmck** [comment]
Need to fix some bugs and do some more performance tweaks and I'll push out a new minor later today.

**Comment by Dashed** [comment]
Saw this floating around: http://jsperf.com/tco/8

Probably good to use this as a benchmark suite for TCO?

**Comment by sebmck** [comment]
@Dashed Probably. This is automated and a handwritten optimised version is always going to be faster.

**Comment by sebmck** [comment]
Although there are some relevant parts in there that @RReverser may be able to change/implement.

**Comment by jabbrass** [comment]
@Dashed Yes, I was just looking into the performance for comparison, and created that jsperf revision. @sebmck Obviously handwritten code will always have an edge, still great to have an automated TCO solution

**Comment by sebmck** [comment]
@jabbrass The transformation/detection is already in place so optimising the helper will be trivial. Super happy to have this finally available.

Available as of 3.5.0

**Comment by Dashed** [comment]
@sebmck Oh yeah, unrolled versions are no doubt faster. On my machine with Chrome Beta, the jsperf demonstrated that 6to5 TCO beat every other handwritten TCO version in that benchmark; which is not bad.

**Comment by RReverser** [comment]
> Actually this can be cleaned up a bit more, but going to sleep, will do that tomorrow.

@sebmck Ah, I hoped to do this before release, but just woke up. Nothing critical, anyway. Thank you for releasing it!

**Comment by sebmck** [comment]
@RReverser Too many people excited for this to wait! Awesome work, really appreciated.

**Comment by MiracleBlue** [comment]
+1 excitement level!  Really looking forward to this.  Thanks!  We love 6to5 at my workplace!

**Comment by RReverser** [comment]
> Yes, I was just looking into the performance for comparison, and created that jsperf revision from a set of benchmarks created several years ago from this gist: https://gist.github.com/Gozala/1697037.

@jabbrass Ah damn, didn't see that, so had to create own implementation. I'll look if we can optimize with those.

**Comment by kobezzza** [comment]
Great news :+1:

**Comment by mikaa123** [comment]
:+1: sharing the excitement here! thanks.

**Comment by hartca** [comment]
Thanks :)

**Comment by camspiers** [comment]
This work is awesome (y) but there is a memory issue with the current implementation.

```
function length(arr, n = 0) {
  return arr[n] === undefined ? n : length(arr, n + 1);
}
```

generates:

```
function length(arr) {
  var _arguments = arguments,
      _this = this,
      _shouldContinue,
      _result;
  do {
    _shouldContinue = false;
    _result = (function (arr) {
      var n = arguments[1] === undefined ? 0 : arguments[1];
      if (arr[n] === undefined) {
        return n;
      } else {
        _arguments = [arr, n + 1];
        _this = undefined;
        return _shouldContinue = true;
      }
    }).apply(_this, _arguments);
  } while (_shouldContinue);
  return _result;
}
```

But as you can see, the function is defined in the loop each time round meaning the the memory will balloon. For example running `length` on an array of size will cause the memory to grow to over 1GB.

If the output is more like:

```

function length(arr) {
  var _arguments = arguments,
      _this = this,
      _shouldContinue,
      _result,
      _fn;

  _fn = (function (arr) {
    var n = arguments[1] === undefined ? 0 : arguments[1];
    if (arr[n] === undefined) {
      return n;
    } else {
      _arguments = [arr, n + 1];
      _this = undefined;
      return _shouldContinue = true;
    }
  });
  do {
    _shouldContinue = false;
    _result = _fn.apply(_this, _arguments);
  } while (_shouldContinue);
  return _result;
}
```

the implementation won't have this memory issue and will also be faster.

**Comment by sebmck** [comment]
@camspiers Yep, that was fixed with ee5cb8d9ede5db14be5b6944f574f295957ddb8e. We're currently working on optimising it even further.

**Comment by camspiers** [comment]
Oh awesome!

**Comment by raganwald** [comment]
Where can I file a complaint? You've just obsoleted both of my blog posts about Trampolining in JavaScript: [Trampolines in JavaScript ](http://raganwald.com/2013/03/28/trampolines-in-javascript.html) and [High Level Trampolining](http://raganwald.com/2013/03/29/high-level-trampolining.html). :skull:

**Comment by raganwald** [comment]
Update: This code obsoletes  [Trampolines in JavaScript ](http://raganwald.com/2013/03/28/trampolines-in-javascript.html), it optimizes tail-recursive functions. But it does not obsolete [High Level Trampolining](http://raganwald.com/2013/03/29/high-level-trampolining.html), it does not rewrite tail-calling functions into trampolined functions, therefore it does not optimize things like co-recursive functions.

For example:

		function even (n) {
		  return n == 0
		    ? true
		    : odd(n - 1);
		};

		function odd (n) {
		  return n == 0
		    ? false
		    : even(n - 1);
		};

**Comment by sebmck** [comment]
@raganwald Not sure what implementation you're referring to since there's two and the one included in this PR isn't in the 6to5 core because there are issues with nested tail calls.

**Comment by RReverser** [comment]
@raganwald @sebmck Looks like we three wanted to write the same thing at the same time :)

**Comment by raganwald** [comment]
> the one included in this PR isn't in the 6to5 core because there are issues with nested tail calls.

Good point. I'll save my gnashing of teeth over obsolescence for when this ships. You probably know this already, but trampolining (as opposed to optimizing for tail-recursive functions) is useful for more than just co-recursion. It solves the problem that this is optimized:

```
function even (n) {
  return n === 0
    ? true
    : (n === 1
         ? false
         : even(n-2)
      );
}
```

But currently, this is not:

```
const even = (n) =>
  n === 0
    ? true
    : (n === 1
         ? false
         : even(n-2)
      );
```

I presume this is because the current tail-recusion optimizer does not recognize that this anonymous function can only ever call itself, unlike the edge case of possibly re-binding `even` in the following snippet:

```
let even = (n) =>
  n === 0
    ? true
    : (n === 1
         ? false
         : even(n-2)
      );
```

**Comment by raganwald** [comment]
@RReverser:

Just to be painfully explicit, it looks like 6to5 turns this:

	function even (n) {
	  return n === 0 ? true : n === 1 ? false : even(n - 2);
	}

Into:

	function even(n) {
	  var _arguments = arguments,
	      _this = this,
	      _shouldContinue,
	      _result;
	  do {
	    _shouldContinue = false;
	    _result = (function (n) {
	      if (n === 0) {
	        return true;
	      } else if (n === 1) {
	        return false;
	      } else {
	        _arguments = [n - 2];
	        _this = undefined;
	        return _shouldContinue = true;
	      }
	    }).apply(_this, _arguments);
	  } while (_shouldContinue);
	  return _result;
	}

Whereas it doesn't do anything special with:

	function even (n) {
	  return n === 0 ? true : odd(n - 1);
	}

	function odd (n) {
	  return n === 0 ? false : even(n - 1);
	}

Meaning, this is optimizing the special case of tail-*recursion*, but not the general case of all tail-*calls*.

Am I correct?

**Comment by RReverser** [comment]
@raganwald Please read carefully previous @sebmck's message.

> Not sure what implementation you're referring to since there's two and the one included in this PR isn't in the 6to5 core because there are issues with nested tail calls.

This PR was attempt for complete tail call optimization, but it had too much edge cases and so 6to5 switched back to #701 which is what you observe.

**Comment by raganwald** [comment]
@RReverser:

Thanks, that is very clear. :gift:

**Pull request merged**
