### PR TITLE
Add --indent option to change indent width

### PR DESCRIPTION
**Pull request by monsanto**
this + doc fix fixes https://github.com/6to5/6to5/issues/414

### CODE REVIEW

**Comment by kevinb7** [comment]
Thanks for creating a pull request for this.  I had a quick look at the code.  I assume the programmatic API remains the same for controller the indentation.

**Comment by sebmck** [comment]
Thanks!

**Comment by sebmck** [comment]
Released as of 2.8.0

**Comment by eventualbuddha** [comment]
Perhaps `--indent auto` would be useful? Other names might be `detect` or `preserve`? Essential an option that figures out what the indent is and uses that.

**Comment by monsanto** [comment]
@eventualbuddha what is the canonical way to determine indentation? I could do something like search for a line matching `/{\s*$/` and determine the whitespace offset relative to the next non-empty line.

**Comment by eventualbuddha** [comment]
@monsanto I'm not sure of a canonical way to do it, but here's [how recast does it](https://github.com/benjamn/recast/blob/753d989bd9af5861b097d695f3ee8861533989eb/lib/lines.js#L385-L423).

**Comment by sebmck** [comment]
So this issue with autodetecting indentation (and why I haven't already done it) is that what if there's no indentation in the current file? It'll lead to inconsistencies in the generated code.

**Comment by monsanto** [comment]
@sebmck maybe fall back to 2 spaces if we can't figure out the indentation?

**Comment by sebmck** [comment]
Yep, but if all your other code uses 4 spaces then it'll lead to inconsistencies. That's the only real reason why I haven't done it so far.

**Comment by sebmck** [comment]
Also I haven't really tested the code generator against different formatting options so it might go a little weird, not too sure.

**Comment by monsanto** [comment]
@sebmck Trying to understand what you mean. Are you are referring to the case where there are multiple files in the project, some with 4 space indentation, some with none, and it would look ugly if the no indentation files had 2 spaces?

If we compile multiple files in one step, could inherit indentation settings from another file. Or could just say it's a corner case and to manually specify indentation if you care. Any non-contrived file without indentation is going to be really small anyway.

**Comment by sebmck** [comment]
@monsanto Yeah that's true. I'll have to revaluate my position. This change would come in 3.0.0 though as it's quite significant.

**Pull request merged**
